# Generated by Django 4.2.1 on 2023-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=100, null=True),
        ),
    ]
