# Generated by Django 4.2.1 on 2023-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.BinaryField(editable=True),
        ),
    ]
