# Generated by Django 4.2.1 on 2023-06-06 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
